/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoprogra2;

import com.raven.datechooser.DateChooser;

import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

public class EditarEventoForm extends javax.swing.JFrame {

    /**
     * Creates new form EditarEventoForm
     */
    private eventosClass eventData = null;
    private DateChooser chDate = new DateChooser();

    public EditarEventoForm(eventosClass evento, boolean par) {
        initComponents();
        chDate.setTextField(jTextField3);
        Color disabledColor = Color.GREEN; // Cambia esto al color que prefieras

        jTextField1.setDisabledTextColor(disabledColor);
        jTextField2.setDisabledTextColor(disabledColor);
        jTextField3.setDisabledTextColor(disabledColor);
        jTextField4.setDisabledTextColor(disabledColor);
        jTextField5.setDisabledTextColor(disabledColor);
        jTextField6.setDisabledTextColor(disabledColor);
        if (!par) {
            jComboBox1.setEnabled(par);
            jComboBox2.setEnabled(par);
            jComboBox3.setEnabled(par);
            jTextField1.setEnabled(par);
            jTextField2.setEnabled(par);
            jTextField3.setEnabled(par);
            jTextField4.setEnabled(par);
            jTextField5.setEnabled(par);
            jTextField6.setEnabled(par);
            jButton1.setEnabled(par);
        }
        jComboBox2.setEnabled(false);
        jTextField5.setEnabled(false);
        jTextField6.setEnabled(false);
        jComboBox3.setEnabled(false);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                    if (jComboBox1.getSelectedItem().equals("DEPORTIVO")) {
                        jComboBox2.setEnabled(true);
                        jTextField5.setEnabled(true);
                        jTextField6.setEnabled(true);
                        jComboBox3.setEnabled(false);
                    } else if (jComboBox1.getSelectedItem().equals("MUSICAL")) {
                        jComboBox3.setEnabled(true);
                        jComboBox2.setEnabled(false);
                        jTextField5.setEnabled(false);
                        jTextField6.setEnabled(false);
                    } else {
                        jComboBox2.setEnabled(false);
                        jTextField5.setEnabled(false);
                        jTextField6.setEnabled(false);
                        jComboBox3.setEnabled(false);
                    }
                }
            }
        });
        eventData = evento;
        jTextField1.setText(evento.getTitulo());
        jTextField2.setText(evento.getDescripcion());
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        String formattedDate = formatter.format(evento.getFecha());
        jTextField3.setText(formattedDate);
        jTextField4.setText(String.valueOf(evento.getMontoAlquiler()));
        jComboBox1.setSelectedItem(evento.getTipoEvento().toString());
        jLabel7.setText(evento.getCodigo());
        if (evento.getTipoEvento().toString().equals("DEPORTIVO")) {
            // search for evento in EventosDeportivosManager
            EventosDeportivosClass eventoExtraData = EventosDeportivosManager.getInstance()
                    .searchEvento(EventosDeportivosManager.getInstance().getEventosList(), evento.getCodigo(), 0);
            jComboBox2.setSelectedItem(eventoExtraData.getTipoDeporte().toString());
            jTextField5.setText(eventoExtraData.getNombreEquipoUno());
            jTextField6.setText(eventoExtraData.getNombreEquipoDos());
        } else if (evento.getTipoEvento().toString().equals("MUSICAL")) {
            EventosMusicalClass eventoExtraData = EventosMusicalManager.getInstance()
                    .searchEvento(EventosMusicalManager.getInstance().getEventosList(), evento.getCodigo(), 0);
            jComboBox3.setSelectedItem(eventoExtraData.getTipoMusical().toString());
        }
        // jLabel7.setText(Usuarios.getCurrentUsuario().getNombreCompleto());

    }

    public EditarEventoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "DEPORTIVO", "MUSICAL", "RELIGIOSO" }));

        jLabel1.setText("Titulo");

        jLabel2.setText("Descripcion");

        jLabel3.setText("Fecha");

        jLabel4.setText("Monto alquiler");

        jLabel5.setText("Equipo 1");

        jLabel6.setText("Equipo 2");

        jComboBox2.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "FUTBOL", "TENIS", "RUGBY", "BASEBALL" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "POP", "ROCK", "RAP", "CLASICA", "REGGEATON", "OTRO" }));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("jLabel7");

        jLabel8.setText("Codigo: ");

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton1)
                                                .addGap(83, 83, 83))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jComboBox1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 116,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jTextField4,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        61, Short.MAX_VALUE)
                                                                                .addComponent(jTextField2)
                                                                                .addComponent(jTextField1))
                                                                        .addComponent(jTextField3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                111,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel4)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                        .addComponent(jTextField6,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                60, Short.MAX_VALUE)
                                                                        .addComponent(jTextField5))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel5,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel6,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)))
                                                        .addComponent(jComboBox2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 166,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jComboBox3, 0,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addContainerGap(122, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addGap(83, 83, 83)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addGap(34, 34, 34)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                .addContainerGap(49, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        Eventos menu = new Eventos();
        menu.setVisible(true);
        this.setVisible(false); // TODO add your handling code here:
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        EventosDeportivosClass eventoDeportivoEditar;
        EventosMusicalClass eventoMusicalEditar;
        EventosReligiosoClass eventoReligiosoEditar;

        eventData.setTitulo(jTextField1.getText());
        eventData.setDescripcion(jTextField2.getText());
        eventData.setMontoAlquiler(Double.parseDouble(jTextField4.getText()));

        // seguintes set
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date parsedDate = new Date();
        // eventData.setFecha(jTextField3.getText());
        // Date date = null;
        try {
            Date date = dateFormat.parse(jTextField3.getText());
            System.out.println("Parsed Date: " + date);
            parsedDate = date;
        } catch (ParseException e) {
            e.printStackTrace();
        }
        // parsedDate = date;
        eventData.setFecha(parsedDate);

        if (jComboBox1.getSelectedItem().equals("DEPORTIVO")) {
            eventData.setTipoEvento(TipoEvento.DEPORTIVO);
            if (EventosDeportivosManager.getInstance()
            .searchEvento(EventosDeportivosManager.getInstance().getEventosList(), eventData.getCodigo(), 0) == null) {
                // Aquí puedes manejar el caso cuando eventoDeportivoEditar es null
                System.out.println("No se encontró el evento deportivo");
                //crear nuevo evento deportivo con el codigo
                String fechaStr = jTextField3.getText();
                SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy"); // Ajusta este formato a la forma en que se introduce la fecha
                Date fecha = null;
                try {
                        fecha = formato.parse(fechaStr);
                } catch (ParseException e) {
                     
                        e.printStackTrace();
                }
                TipoEventoDeportivo selectedEvento = TipoEventoDeportivo.FUTBOL;
                if (jComboBox2.getSelectedItem().equals("FUTBOL")) {
                    selectedEvento = TipoEventoDeportivo.FUTBOL;
                } else if (jComboBox2.getSelectedItem().equals("TENIS")) {
                    selectedEvento = TipoEventoDeportivo.TENIS;
                } else if (jComboBox2.getSelectedItem().equals("RUGBY")) {
                    selectedEvento = TipoEventoDeportivo.RUGBY;
                } else if (jComboBox2.getSelectedItem().equals("BASEBALL")) {
                    selectedEvento = TipoEventoDeportivo.BASEBALL;
                }
                EventosDeportivosClass eventoDeportivo = new EventosDeportivosClass(eventData.getCodigo(), jTextField1.getText(), jTextField2.getText(), fecha, eventData.getMontoAlquiler(), TipoEvento.DEPORTIVO, UsuariosManager.getInstance().getCurrentUsuario(), selectedEvento,jTextField5.getText(),jTextField6.getText());
                eventoDeportivoEditar = eventoDeportivo;
                EventosDeportivosManager.getInstance().addEvento(eventoDeportivo);
            }else{
            eventoDeportivoEditar = EventosDeportivosManager.getInstance().searchEvento(EventosDeportivosManager.getInstance().getEventosList(), eventData.getCodigo(), 0);
            }
            
                
            eventoDeportivoEditar.setTitulo(eventData.getTitulo());
            eventoDeportivoEditar.setDescripcion(eventData.getDescripcion());
            eventoDeportivoEditar.setFecha(eventData.getFecha());
            double monto = (eventData.getMontoAlquiler() * 0.3) + eventData.getMontoAlquiler();
            eventoDeportivoEditar.setMontoAlquiler(monto);
            eventoDeportivoEditar.setTipoEvento(TipoEvento.DEPORTIVO);
            eventoDeportivoEditar.setTipoDeporte(TipoEventoDeportivo.valueOf(jComboBox2.getSelectedItem().toString()));
            eventoDeportivoEditar.setNombreEquipoUno(jTextField5.getText());
            eventoDeportivoEditar.setNombreEquipoDos(jTextField6.getText());
            System.out.println("deportivo");
        } else if (jComboBox1.getSelectedItem().equals("MUSICAL")) {
            System.out.println("musical");
            eventData.setTipoEvento(TipoEvento.MUSICAL);
                if (EventosMusicalManager.getInstance().searchEvento(EventosMusicalManager.getInstance().getEventosList(), eventData.getCodigo(), 0) == null) {
                // Aquí puedes manejar el caso cuando eventoMusicalEditar es null
                System.out.println("No se encontró el evento musical");
                //crear nuevo evento musical con el codigo
                String fechaStr = jTextField3.getText();
                SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy"); // Ajusta este formato a la forma en que se introduce la fecha
                Date fecha = null;
                try {
                        fecha = formato.parse(fechaStr);
                } catch (ParseException e) {
                     
                        e.printStackTrace();
                }
                TipoMusical selectedEvento = TipoMusical.POP;
                if (jComboBox3.getSelectedItem().equals("POP")) {
                    selectedEvento = TipoMusical.POP;
                } else if (jComboBox3.getSelectedItem().equals("ROCK")) {
                    selectedEvento = TipoMusical.ROCK;
                } else if (jComboBox3.getSelectedItem().equals("RAP")) {
                    selectedEvento = TipoMusical.RAP;
                } else if (jComboBox3.getSelectedItem().equals("CLASICA")) {
                    selectedEvento = TipoMusical.CLASICA;
                } else if (jComboBox3.getSelectedItem().equals("REGGEATON")) {
                    selectedEvento = TipoMusical.REGGEATON;
                } else if (jComboBox3.getSelectedItem().equals("OTRO")) {
                    selectedEvento = TipoMusical.OTRO;
                }
                String texto = jTextField4.getText();
                double numero = Double.parseDouble(texto);
                double total = (numero * 0.3) + numero;
                EventosMusicalClass eventoMusical = new EventosMusicalClass(eventData.getCodigo(), jTextField1.getText(), jTextField2.getText(), fecha, total, TipoEvento.MUSICAL, UsuariosManager.getInstance().getCurrentUsuario(), selectedEvento);
                eventoMusicalEditar = eventoMusical;
                    EventosMusicalManager.getInstance().addEvento(eventoMusical);
            }else{
                eventoMusicalEditar = EventosMusicalManager.getInstance().searchEvento(EventosMusicalManager.getInstance().getEventosList(), eventData.getCodigo(), 0);
                }


            eventoMusicalEditar = EventosMusicalManager.getInstance()
                    .searchEvento(EventosMusicalManager.getInstance().getEventosList(), eventData.getCodigo(), 0);
            eventoMusicalEditar.setTitulo(eventData.getTitulo());
            eventoMusicalEditar.setDescripcion(eventData.getDescripcion());
            eventoMusicalEditar.setFecha(eventData.getFecha());
            double monto = eventData.getMontoAlquiler() + 2000;
            eventoMusicalEditar.setMontoAlquiler(eventData.getMontoAlquiler());
            eventoMusicalEditar.setTipoEvento(TipoEvento.MUSICAL);
            eventoMusicalEditar.setTipoMusical(TipoMusical.valueOf(jComboBox3.getSelectedItem().toString()));

        } else if (jComboBox1.getSelectedItem().equals("RELIGIOSO")) {
            System.out.println("religioso");
            eventData.setTipoEvento(TipoEvento.RELIGIOSO);
        }
        JOptionPane.showMessageDialog(null, "Modificado, regresando al submenu eventos");
        Eventos menu = new Eventos();
        menu.setVisible(true);
        this.setVisible(false); // TODO add your handling code here:

    }// GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEventoForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEventoForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEventoForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEventoForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarEventoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
