/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoprogra2;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

public class EliminarEvento extends javax.swing.JFrame {

    /**
     * Creates new form EliminarEvento
     */
    public EliminarEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE));
        jFrame1Layout.setVerticalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Eliminar Evento");

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo Evento");

        jButton2.setText("Buscar para eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(164, 164, 164)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(84, 84, 84)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 92,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(60, 60, 60)
                                                .addComponent(jLabel2)))
                                .addContainerGap(84, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(jButton1)
                                                        .addGap(26, 26, 26))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(jButton2)
                                                        .addGap(119, 119, 119)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jButton1)
                                                .addGap(20, 20, 20))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jTextField1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(49, 49, 49)
                                                .addComponent(jButton2)
                                                .addContainerGap(101, Short.MAX_VALUE)))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // JOptionPane.showMessageDialog(null, "REGRESANDO AL SUBMENU EVENTOS");
        Eventos menu = new Eventos();
        menu.setVisible(true);
        this.setVisible(false); // TODO add your handling code here:
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        String code = jTextField1.getText();
        eventosClass evento = EventosManager.getInstance().searchEvento(EventosManager.getInstance().getEventosList(),
                code, 0);
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que quieres cancelar el evento? si esta en un rango de un dia se cobrara el 50% por indemnizacion si es deporte o musica.",
                "Confirmar cancelación", JOptionPane.YES_NO_CANCEL_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            if (evento != null) {
                System.out.println("evento no es nulo");
                if (UsuariosManager.getCurrentUsuario().equals(evento.getCreatedBy())) {

                    System.out.println("el usuario es el que lo creo");
                    // Resto del código...
                    evento.setIsActive(true);
                    // Resto del código...
                    if (evento.getTipoEvento() == TipoEvento.DEPORTIVO || evento.getTipoEvento() == TipoEvento.MUSICAL
                            || evento.getTipoEvento() == TipoEvento.SELECT) {
                        // Convertir la fecha a SimpleDateFormat
                        System.out.println(evento.getTipoEvento() == TipoEvento.DEPORTIVO);
                        System.out.println(evento.getTipoEvento() == TipoEvento.MUSICAL);
                        System.out.println(evento.getTipoEvento() == TipoEvento.SELECT);
                        SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
                        String fechaStr = formato.format(evento.getFecha());

                        Date fechaActual = new Date();
                        Calendar cal = Calendar.getInstance();
                        cal.setTime(fechaActual);

                        Calendar calEvento = Calendar.getInstance();
                        calEvento.setTime(evento.getFecha());

                        // Comparar la fecha del evento con la fecha de hoy y mañana
                        // imprimir
                        System.out.println("fecha evento: " + evento.getFecha());
                        System.out.println("Fecha actual: " + fechaActual);

                        // Sumar 1 día a la fecha actual
                        cal.add(Calendar.DATE, 1);
                        Date fechaMañana = cal.getTime();

                        // Calculate the difference in days between the event date and today's date
                        long daysDifference = (calEvento.getTimeInMillis() - cal.getTimeInMillis())
                                / (1000 * 60 * 60 * 24);

                        if (Math.abs(daysDifference) > 1) {
                            System.out.println("The event date is not within a range of 1 day from today.");
                        } else {
                            // Si el evento es hoy o mañana, cobrar el 50% de montoAlquiler
                            double montoCobrado = evento.getMontoAlquiler() * 0.5;
                            JOptionPane.showMessageDialog(null,
                                    "Se ha cobrado el 50% de montoAlquiler por estar en rango de 1 dia: "
                                            + montoCobrado);
                            evento.setMontoAlquiler(montoCobrado);
                        }
                        // Resto del código...
                        evento.setIsActive(true);
                        JOptionPane.showMessageDialog(null, "Eliminado logico evento cancelado");
                    }
                    if (evento.getTipoEvento() == TipoEvento.RELIGIOSO) {
                        // Si el evento es religioso y tiene menos de una semana para comenzar,
                        System.out.println(evento.getTipoEvento() == TipoEvento.RELIGIOSO);
                        EventosReligiososManager.getInstance()
                                .searchEvento(EventosReligiososManager.getInstance().getEventosList(), code, 0)
                                .setIsActive(true);
                        JOptionPane.showMessageDialog(null, "Eliminado logico evento cancelado religioso");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario actual no es el creador del evento");
                }

            } else

            {
                JOptionPane.showMessageDialog(null, "No se encontró el evento con el código proporcionado");
            }
        } else if (respuesta == JOptionPane.NO_OPTION) {
            // Aquí va el código para no cancelar el evento
        } else {
            // Aquí va el código para la opción "Cancelar"
        }

    }// GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
