/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoprogra2;

import datechooser.beans.DateChooserCombo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
public class ReportesSubmenu extends javax.swing.JFrame {

    /**
     * Creates new form ReportesSubmenu
     */
    
    List<eventosClass> eventosList = EventosManager.getInstance().getEventosList();
    List<eventosClass> modify = new ArrayList<>(eventosList);
    String columns[]={ "Codigo", "Titulo", "Descripcion", "Fecha", "Monto Alquiler", "Tipo Evento", "Creado por","Capacidad máxima","Tipo deporte", "Equipo 1", "Equipo 2","Tipo Musica","Cancelado"};
    public ReportesSubmenu() {
        initComponents();
        EventosTableModel model = new EventosTableModel(modify, columns);
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonListarEventosRealizados = new javax.swing.JButton();
        buttonListarEventosFuturos = new javax.swing.JButton();
        buttonListarEventosCancelados = new javax.swing.JButton();
        buttonIngresadoPorFecha = new javax.swing.JButton();
        buttonVerPerfilDelUsuario = new javax.swing.JButton();
        buttonRegresar = new javax.swing.JButton();
        buttonResetFilters = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        buttonListarEventosRealizados.setText("Listar Eventos Realizados");
        buttonListarEventosRealizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListarEventosRealizadosActionPerformed(evt);
            }
        });

        buttonListarEventosFuturos.setText("Listar Eventos Futuros");
        buttonListarEventosFuturos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListarEventosFuturosActionPerformed(evt);
            }
        });

        buttonListarEventosCancelados.setText("Listar Eventos Cancelados");
        buttonListarEventosCancelados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListarEventosCanceladosActionPerformed(evt);
            }
        });

        buttonIngresadoPorFecha.setText("Ingreso generado por fecha");
        buttonIngresadoPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIngresadoPorFechaActionPerformed(evt);
            }
        });

        buttonVerPerfilDelUsuario.setText("Ver Perfil del Usuario");
        buttonVerPerfilDelUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerPerfilDelUsuarioActionPerformed(evt);
            }
        });

        buttonRegresar.setText("Regresar");
        buttonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegresarActionPerformed(evt);
            }
        });

        buttonResetFilters.setText("Reset filters");
        buttonResetFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetFiltersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonRegresar)
                        .addGap(82, 82, 82)
                        .addComponent(buttonListarEventosRealizados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonListarEventosFuturos)
                        .addGap(18, 18, 18)
                        .addComponent(buttonListarEventosCancelados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonIngresadoPorFecha)
                        .addGap(18, 18, 18)
                        .addComponent(buttonVerPerfilDelUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(buttonResetFilters)
                        .addGap(135, 135, 135))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRegresar)
                    .addComponent(buttonListarEventosRealizados)
                    .addComponent(buttonListarEventosFuturos)
                    .addComponent(buttonListarEventosCancelados)
                    .addComponent(buttonIngresadoPorFecha)
                    .addComponent(buttonVerPerfilDelUsuario)
                    .addComponent(buttonResetFilters))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegresarActionPerformed
 menu e = new menu();
        e.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRegresarActionPerformed

    private void buttonListarEventosRealizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListarEventosRealizadosActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Filtrando datos que ya han pasado...");
        modify.clear();
        for(eventosClass evento : eventosList){
            if(evento.getFecha().before(new Date())){
                modify.add(evento);
            }
        }
        EventosTableModel model = new EventosTableModel(modify, columns);
        jTable1.setModel(model);
    }//GEN-LAST:event_buttonListarEventosRealizadosActionPerformed

    private void buttonListarEventosFuturosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListarEventosFuturosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Filtrando datos que aun no han pasado...");
        modify.clear();
        for(eventosClass evento : eventosList){
            if(evento.getFecha().after(new Date())){
                modify.add(evento);
            }
        }
        EventosTableModel model = new EventosTableModel(modify, columns);
        jTable1.setModel(model);
    }//GEN-LAST:event_buttonListarEventosFuturosActionPerformed

    private void buttonListarEventosCanceladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListarEventosCanceladosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Filtrando datos que han sido cancelados...");
        modify.clear();
        for(eventosClass evento : eventosList){
            if(evento.getIsActive() == true){
                modify.add(evento);
            }
        }
        EventosTableModel model = new EventosTableModel(modify, columns);
        jTable1.setModel(model);
    }//GEN-LAST:event_buttonListarEventosCanceladosActionPerformed

    private void buttonIngresadoPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIngresadoPorFechaActionPerformed

            // Crear un JDialog
            JDialog dialog = new JDialog();
            dialog.setModal(true);
            dialog.setTitle("Seleccionar rango de fechas");

            // Crear dos DateChooserCombos
            DateChooserCombo startDateChooser = new DateChooserCombo();
            DateChooserCombo endDateChooser = new DateChooserCombo();

            // Crear un botón para confirmar la selección
            JButton confirmButton = new JButton("Confirmar");
            confirmButton.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    Calendar startDate = startDateChooser.getSelectedDate();
                   Calendar endDate = endDateChooser.getSelectedDate();

                    // Aquí puedes filtrar tus datos por las fechas seleccionadas
                    // y actualizar tu modelo de tabla
                    JOptionPane.showMessageDialog(null, "Filtrando datos por fecha ingresada por el usuario...");
        modify.clear();
        for(eventosClass evento : eventosList){
            if(evento.getFecha().after(startDate.getTime()) && evento.getFecha().before(endDate.getTime())){
                modify.add(evento);
            }
        }
       
        EventosTableModel model = new EventosTableModel(modify, columns);
        jTable1.setModel(model);

                    // Cerrar el diálogo
                    dialog.dispose();
                }
            });

            // Añadir los DateChooserCombos y el botón al diálogo
            JPanel panel = new JPanel();
            panel.add(new JLabel("Fecha de inicio:"));
            panel.add(startDateChooser);
            panel.add(new JLabel("Fecha de fin:"));
            panel.add(endDateChooser);
            panel.add(confirmButton);
            dialog.getContentPane().add(panel);

            // Mostrar el diálogo
            dialog.pack();
            dialog.setVisible(true);
        
    }//GEN-LAST:event_buttonIngresadoPorFechaActionPerformed

    private void buttonResetFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetFiltersActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Restableciendo datos...");
        modify.clear();
        modify.addAll(eventosList);
        EventosTableModel model = new EventosTableModel(modify, columns);
        jTable1.setModel(model);

    }//GEN-LAST:event_buttonResetFiltersActionPerformed

    private void buttonVerPerfilDelUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerPerfilDelUsuarioActionPerformed
        // TODO add your handling code here:
        //abrir un modal mostrando todos los datos del usuario
        JOptionPane.showMessageDialog(null, "Abriendo perfil del usuario...");
        Usuarios user = UsuariosManager.getInstance().getCurrentUsuario();

        // Crear un JDialog
        JDialog dialog = new JDialog();
        dialog.setModal(true);
        dialog.setTitle("Perfil del usuario");

        // Crear un JPanel para contener los datos del usuario
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));

        // Añadir los datos del usuario al panel
        panel.add(new JLabel("Nombre completo: " + user.getNombreCompleto()));
        panel.add(new JLabel("Username: " + user.getUsername()));
        panel.add(new JLabel("Password: " + user.getPassword()));
        panel.add(new JLabel("Edad: " + user.getEdad()));
        panel.add(new JLabel("Tipo de usuario: " + user.getTipoUsuario()));
        panel.add(new JLabel("IDs de eventos creados: " + user.getIdsEventosCreados()));

        // Añadir el panel al diálogo
        dialog.getContentPane().add(panel);

        // Mostrar el diálogo
        dialog.pack();
        dialog.setVisible(true);

    }//GEN-LAST:event_buttonVerPerfilDelUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportesSubmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportesSubmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportesSubmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportesSubmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportesSubmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonIngresadoPorFecha;
    private javax.swing.JButton buttonListarEventosCancelados;
    private javax.swing.JButton buttonListarEventosFuturos;
    private javax.swing.JButton buttonListarEventosRealizados;
    private javax.swing.JButton buttonRegresar;
    private javax.swing.JButton buttonResetFilters;
    private javax.swing.JButton buttonVerPerfilDelUsuario;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
